################################################################################
## Form generated from reading UI file 'findfuncdialog.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QSize, Qt)
from PySide6.QtWidgets import (QAbstractScrollArea, QCheckBox, QGridLayout, QHBoxLayout, QPushButton, QSizePolicy, QSplitter, QTableView, QVBoxLayout, QWidget)

class Ui_FindFunc(object):
    def setupUi(self, FindFunc):
        if not FindFunc.objectName():
            FindFunc.setObjectName(u"FindFunc")
        FindFunc.resize(915, 459)
        self.horizontalLayout_3 = QHBoxLayout(FindFunc)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.splitter = QSplitter(FindFunc)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.tableresults = QTableView(self.splitter)
        self.tableresults.setObjectName(u"tableresults")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableresults.sizePolicy().hasHeightForWidth())
        self.tableresults.setSizePolicy(sizePolicy)
        self.tableresults.setMinimumSize(QSize(0, 0))
        self.tableresults.setMaximumSize(QSize(16777215, 16777215))
        self.tableresults.setBaseSize(QSize(0, 0))
        self.tableresults.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.splitter.addWidget(self.tableresults)
        self.tableresults.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tableview = QTableView(self.layoutWidget)
        self.tableview.setObjectName(u"tableview")
        self.tableview.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableview)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.btnaddimm = QPushButton(self.layoutWidget)
        self.btnaddimm.setObjectName(u"btnaddimm")
        self.gridLayout.addWidget(self.btnaddimm, 1, 0, 1, 1)
        self.btnfuncsize = QPushButton(self.layoutWidget)
        self.btnfuncsize.setObjectName(u"btnfuncsize")
        self.gridLayout.addWidget(self.btnfuncsize, 0, 0, 1, 1)
        self.btnaddstr = QPushButton(self.layoutWidget)
        self.btnaddstr.setObjectName(u"btnaddstr")
        self.gridLayout.addWidget(self.btnaddstr, 0, 1, 1, 1)
        self.btnaddname = QPushButton(self.layoutWidget)
        self.btnaddname.setObjectName(u"btnaddname")
        self.gridLayout.addWidget(self.btnaddname, 1, 1, 1, 1)
        self.btnaddcode = QPushButton(self.layoutWidget)
        self.btnaddcode.setObjectName(u"btnaddcode")
        self.gridLayout.addWidget(self.btnaddcode, 1, 2, 1, 1)
        self.btnaddpattern = QPushButton(self.layoutWidget)
        self.btnaddpattern.setObjectName(u"btnaddpattern")
        self.gridLayout.addWidget(self.btnaddpattern, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.chkdebug = QCheckBox(self.layoutWidget)
        self.chkdebug.setObjectName(u"chkdebug")
        self.verticalLayout.addWidget(self.chkdebug)
        self.chkprofile = QCheckBox(self.layoutWidget)
        self.chkprofile.setObjectName(u"chkprofile")
        self.verticalLayout.addWidget(self.chkprofile)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.btnsearch = QPushButton(self.layoutWidget)
        self.btnsearch.setObjectName(u"btnsearch")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.btnsearch.sizePolicy().hasHeightForWidth())
        self.btnsearch.setSizePolicy(sizePolicy1)
        self.horizontalLayout_2.addWidget(self.btnsearch)
        self.btnrefine = QPushButton(self.layoutWidget)
        self.btnrefine.setObjectName(u"btnrefine")
        sizePolicy1.setHeightForWidth(self.btnrefine.sizePolicy().hasHeightForWidth())
        self.btnrefine.setSizePolicy(sizePolicy1)
        self.horizontalLayout_2.addWidget(self.btnrefine)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter.addWidget(self.layoutWidget)
        self.horizontalLayout_3.addWidget(self.splitter)

        self.retranslateUi(FindFunc)
        QMetaObject.connectSlotsByName(FindFunc)

    def retranslateUi(self, FindFunc):
        FindFunc.setWindowTitle(QCoreApplication.translate("FindFunc", u"Filter Signatures", None))
        self.btnaddimm.setText(QCoreApplication.translate("FindFunc", u"Immediate/Constant ref", None))
        self.btnfuncsize.setText(QCoreApplication.translate("FindFunc", u"Function size", None))
        self.btnaddstr.setText(QCoreApplication.translate("FindFunc", u"String reference", None))
        self.btnaddname.setText(QCoreApplication.translate("FindFunc", u"Name reference", None))
        self.btnaddcode.setText(QCoreApplication.translate("FindFunc", u"Code pattern", None))
        self.btnaddpattern.setText(QCoreApplication.translate("FindFunc", u"Byte pattern", None))
        self.chkdebug.setText(QCoreApplication.translate("FindFunc", u"Debug", None))
        self.chkprofile.setText(QCoreApplication.translate("FindFunc", u"Profile", None))
        self.btnsearch.setText(QCoreApplication.translate("FindFunc", u"Find functions", None))
        self.btnrefine.setText(QCoreApplication.translate("FindFunc", u"Refine", None))
